<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>36c10cc0-d75e-4bbb-9798-c1e28774d85e</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="9.2.2" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="9.2.2" />
        <PackageReference Include="MediatR" Version="14.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MedCareOS.Application\MedCareOS.Application.csproj" />
      <ProjectReference Include="..\MedCareOS.Infrastructure\MedCareOS.Infrastructure.csproj" />
    </ItemGroup>

</Project>
